from datetime import datetime
from dataclasses import dataclass, field


@dataclass
class JobLink:
    """
    A class to store links to job postings.

    Attributes:
        url (str): The URL to the job page.
        raw_text (str): The associated raw text scraped from the HTML tag containing the link.
        date_scraped (str): An autogenerated string containing the date and time of instantiation.
    """

    url: str
    raw_text: str
    # "field" ensures that the timestamp is computed each time an instance of JobLink is created, not globally
    date_scraped: str = field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d %H:%M:%S"), init=False)

    def __str__(self) -> str:
        return (
            f"URL: {self.url}\n"
            f"Raw Text: {self.raw_text or 'N/A'}\n"
            f"Date Scraped: {self.date_scraped}"
        )
