from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class JobPageEntry:
    """
    A class to store information about a fetched web page.

    Attributes: 
        url (str): The URL to the job page. file_name (str): The name of the file containing 
        the web page HTML. 
        date_scraped (str): An autogenerated string containing the date and time of instantiation, 
        unless provided explicitly.
    """
    url: str
    file_name: str
    date_scraped: Optional[str] = None  # allow passing or leave empty


    def __post_init__(self):
        if self.date_scraped is None:
            self.date_scraped = datetime.now().strftime("%Y-%m-%d %H:%M:%S")


    def __str__(self) -> str:
        return (
            f"URL: {self.url}\n"
            f"File Name: {self.file_name}\n"
            f"Date Scraped: {self.date_scraped}"
        )
