from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class JobPageEntry:
    """
    A class to store information about a fetched web page.

    Attributes:
        url (str): The URL to the job page.
        file_name (str): The name of the file containing the web page HTML.
        date_scraped (str): An autogenerated string containing the date and time of instantiation.
    """

    url: str
    file_name: str
    # "field" ensures that the timestamp is computed each time an instance of JobLink is created, not globally
    date_scraped: str = field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d %H:%M:%S"), init=False)

    def __str__(self) -> str:
        return (
            f"URL: {self.url}\n"
            f"File Name: {self.file_name}\n"
            f"Date Scraped: {self.date_scraped}"
        )
