from datetime import datetime
from dataclasses import dataclass
from typing import Optional


@dataclass
class JobLink:
    """
    A class to store links to job postings.

    Attributes:
        url (str): The URL to the job page.
        raw_text (str): The associated raw text scraped from the HTML tag containing the link.
        date_scraped (str): An autogenerated string containing the date and time of instantiation, 
        unless provided explicitly.
    """
    url: str
    raw_text: str
    date_scraped: Optional[str] = None  # allow passing or leave empty


    def __post_init__(self):
        if self.date_scraped is None:
            self.date_scraped = datetime.now().strftime("%Y-%m-%d %H:%M:%S")


    def __str__(self) -> str:
        return (
            f"URL: {self.url}\n"
            f"Raw Text: {self.raw_text or 'N/A'}\n"
            f"Date Scraped: {self.date_scraped}"
        )
